# backend/alembic/versions/47513efa9fba_add_created_at_to_transactions.py
"""add created_at to transactions

Revision ID: 47513efa9fba
Revises: 
Create Date: 2026-07-16 04:27:01.467882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47513efa9fba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ... inside def upgrade() ...
    
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=4),
               type_=sa.Enum('BUY', 'SELL', name='transactiontype'),
               existing_nullable=False,
               postgresql_using="transaction_type::transactiontype")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'transaction_type',
               existing_type=sa.Enum('BUY', 'SELL', name='transactiontype'),
               type_=sa.VARCHAR(length=4),
               existing_nullable=False)
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###
