"""Add MeroShare credentials to User model

Revision ID: c1c52a93f456
Revises: f6585e49743a
Create Date: 2026-07-31 00:55:58.565036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c52a93f456'
down_revision: Union[str, None] = 'f6585e49743a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('meroshare_dp_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('meroshare_username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('meroshare_password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'meroshare_password')
    op.drop_column('users', 'meroshare_username')
    op.drop_column('users', 'meroshare_dp_id')
    # ### end Alembic commands ###
